# version: "3.9"     specifying the version is not recommended by Docker

services:
  db:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: task_user
      POSTGRES_PASSWORD: task_pass
      POSTGRES_DB: mytasksdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:54s32"
    networks:
      - task-network

  backend:
    build: ./backend
    container_name: backend_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/mytasksdb
      SPRING_DATASOURCE_USERNAME: task_user
      SPRING_DATASOURCE_PASSWORD: task_pass
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    networks:
      - task-network

  frontend:
    build: ./frontend
    container_name: frontend_app
    depends_on:
      - backend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: http://backend:8080
    networks:
      - task-network

volumes:
  postgres_data:

networks:
  task-network:
    driver: bridge